### PR TITLE
Asynchronous captures to have longer kinect sequences

### PR DESCRIPTION
**Pull request by raffienficiaud**
This is part 1/2 of the PR. 
We changes the code in order to have an asynchronous capture scheme and to enable longer capture sequences. The captured frames are now stored in a memory pool from the capture thread, and threads from a thread pool are saving these frames to disk during the capture. 

Part of the processing is also delayed to the saving threads to have 30fps in the capture thread.

### CODE REVIEW

**Comment by chenliu0831** [comment]
Thanks @raffienficiaud for contributing. Awesome features and I'll review it as soon as I switch back to windows :)

**Comment by raffienficiaud** [comment]
I just created the second PR in the monocle repository. Please let us know if there is something more we can do.

**Comment by raffienficiaud** [comment]
Hi, did you have the chance to review the PR?

**Comment by chenliu0831** [comment]
Hey @raffienficiaud, sorry we've been a little rocky recently. Let me figure out a time to sort it out...

**Comment by raffienficiaud** [comment]
Hi @chenliu0831 

Any news? Do you need any help?

**Comment by chenliu0831** [comment]
Hey @raffienficiaud 

Sorry for keeping this open for so long. I'm going to review those changes tonight.

cc Paul. @paulmelnikow

**Comment by raffienficiaud** [comment]
Thanks!

**Comment by chenliu0831** [comment]
@raffienficiaud Just took a shallow pass. Actually in the not-yet-open-sourced part of this framework, we were doing some similar P-C queue thing but just for the visualization part. This PR is great as it seems to also extend it to the serialization part. 

That being said, it looks like we were using some higher level primitives of .Net like `BlockingCollection` and `Task` to manage workers and  `ConcurrentQueue` for reuse free items. Here it seems more low-level but I would like to do a more detailed comparison and probably combine the goodies. If possible please take a look at those primitives and I'll try to make our implementation of this part open-sourced asap. 

Thanks! More detailed review will be upcoming.

**Comment by raffienficiaud** [comment]
My turn to apologize, I am a bit busy these days... Thank you for your feedback. I was not aware of these classes and apparently we reinvented the wheel again. We will look at those class and modify the code accordingly (Apparently there is also the ThreadPool.QueueUserWorkItem that might fit better).

**Comment by chenliu0831** [comment]
@raffienficiaud Absolutely no problem! We are going through all kinds of sprint as well. Hopefully we could get some large bulk of spare time near the autumn lol.

**Comment by raffienficiaud** [comment]
We will not have the resource to work on this, sorry!

**Pull request closed without merging**
